src/main/java/strona/bazapracownikow/view/LanguageBean.java
package strona.bazapracownikow.view;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import javax.inject.Named;

/**
 *
 * @author shandnyar
 */
@Named
@SessionScoped
public class LanguageBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private String localeCode;

    private static Map<String, Locale> countries;

    static {
        countries = new LinkedHashMap<String, Locale>();
        countries.put("Polski", new Locale("pl"));
//        countries.put("English", Locale.ENGLISH);
        countries.put("Deutsch", Locale.GERMAN);
    }

    public Map<String, Locale> getCountriesInMap() {
        return countries;
    }

    public String getLocaleCode() {
        return localeCode;
    }

    public void setLocaleCode(String localeCode) {
        this.localeCode = localeCode;
    }

    //value change event listener
    public void countryLocaleCodeChanged(ValueChangeEvent e) {

        localeCode = e.getNewValue().toString();

        //loop country map to compare the locale code
        for (Map.Entry<String, Locale> entry : countries.entrySet()) {

            if (entry.getValue().toString().equals(localeCode)) {

                FacesContext.getCurrentInstance()
                        .getViewRoot().setLocale((Locale) entry.getValue());

            }
        }
    }

}

src/main/webapp/tpl/layout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
    <f:view locale="#{languageBean.localeCode}">
        <h:head>
            <meta charset="UTF-8" />
            <title><ui:insert name="title"></ui:insert> BazaPracowników</title>
            <h:outputStylesheet library="css" name="bootstrap.min.css" />
            <h:outputStylesheet library="css" name="bootstrap-theme.min.css" />
            <h:outputScript library="js" name="bootstrap.min.js" />
            <style>
                body {
                    padding-top: 100px;
                }
            </style>
        </h:head>
        <h:body>
            <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">BazaPracowników</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <h:form styleClass="navbar-form">
                                <h:selectOneMenu styleClass="form-control" value="#{languageBean.localeCode}" onchange="submit()"
                                                 valueChangeListener="#{languageBean.countryLocaleCodeChanged}">
                                    <f:selectItems value="#{languageBean.countriesInMap}" /> 
                                </h:selectOneMenu>
                            </h:form>
                        </li>
                        <c:choose>
                            <c:when test="${empty loginBean.manager}">
                                <li><p class="navbar-text"><a href="login.jsf" class="navbar-link">#{msg.login}</a></p></li>
                                <li><p class="navbar-text"><a href="addManager.jsf" class="navbar-link">#{msg.register}</a></p></li>
                            </c:when>
                            <c:otherwise>
                                <li><p class="navbar-text"><a href="addDepartment.jsf">#{msg.addDepartment}</a></p></li>
                                <li><p class="navbar-text"><a href="addWorker.jsf">#{msg.addWorker}</a></p></li>
                                <li><p class="navbar-text">#{msg.welcome} #{loginBean.manager.firstName} #{loginBean.manager.lastName}</p></li>
                                <li><p class="navbar-text"><h:form styleClass="navbar-form"><h:commandLink action="#{loginBean.logout()}" value="#{msg.logout}" /></h:form></p></li>
                            </c:otherwise>
                        </c:choose>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </nav>
            <div class="container">
                <div class="col-md-8">
                    <ui:insert name="content" />
                </div>
                <div class="col-md-4">
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#">#{msg.homepage}</a></li>
                        <li><a href="showDepartments.jsf">#{msg.department}</a></li>
                        <li><a href="showWorkers.jsf">#{msg.worker}</a></li>
                    </ul>
                </div>
            </div>
        </h:body>
    </f:view>
</html>