src/main/java/strona/bazapracownikow/model/domain/Department.java
package strona.bazapracownikow.model.domain;

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 *
 * @author shandnyar
 */
@Entity
public class Department extends EntityImpl { 
    
    @Column(nullable = false, unique = true)
    private String name;
    
    @OneToMany(mappedBy = "department", fetch = FetchType.EAGER)
    private Set<Worker> workers;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<Worker> getWorkers() {
        return workers;
    }

    public void setWorkers(Set<Worker> workers) {
        this.workers = workers;
    }
    
    
}

src/main/java/strona/bazapracownikow/model/domain/EntityImpl.java
package strona.bazapracownikow.model.domain;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

@MappedSuperclass
abstract class EntityImpl {
    
    @Id
    @GeneratedValue
    private long id;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
    
}

src/main/java/strona/bazapracownikow/model/domain/Manager.java
package strona.bazapracownikow.model.domain;

import javax.persistence.Column;
import javax.persistence.Entity;

@Entity
public class Manager extends EntityImpl{
    
    @Column(nullable = false, unique = true, updatable = false)
    private String email;
    @Column(nullable = false)
    private String password;
    @Column(nullable = false)
    private String firstName;
    @Column(nullable = false)
    private String lastName;
    
    private boolean stillWorking;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public boolean isStillWorking() {
        return stillWorking;
    }

    public void setStillWorking(boolean stillWorking) {
        this.stillWorking = stillWorking;
    }
    
    
    
}

src/main/java/strona/bazapracownikow/model/domain/Worker.java
package strona.bazapracownikow.model.domain;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.PreUpdate;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Worker extends EntityImpl implements Serializable {
    
    private String firstName;
    private String lastName;
    @Temporal(TemporalType.DATE)
    private Date dateOfBirth;
    private double salary;
    @Temporal(TemporalType.TIMESTAMP)
    private Date created = new Date();
    @Temporal(TemporalType.TIMESTAMP)
    private Date updated = new Date();
    
    private boolean stillWorking;
    
    @ManyToOne
    private Department department;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public double getSalary() {
        return salary;
    }

    public void setSalary(double salary) {
        this.salary = salary;
    }
    
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Date getUpdated() {
        return updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public boolean isStillWorking() {
        return stillWorking;
    }

    public void setStillWorking(boolean stillWorking) {
        this.stillWorking = stillWorking;
    }
    
}

src/main/java/strona/bazapracownikow/model/service/DepartmentRepository.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package strona.bazapracownikow.model.service;

import strona.bazapracownikow.model.domain.Department;
import strona.bazapracownikow.utils.CrudRepository;

/**
 *
 * @author shandnyar
 */
public interface DepartmentRepository extends CrudRepository<Department, Long>{
    public boolean isDepartmentDuplicated(String name);
}

src/main/java/strona/bazapracownikow/model/service/ManagerRepository.java
package strona.bazapracownikow.model.service;

import strona.bazapracownikow.model.domain.Manager;
import strona.bazapracownikow.utils.CrudRepository;

public interface ManagerRepository extends CrudRepository<Manager, Long>{
    public Manager validManager(String email, String password);
    public boolean isManagerDuplicated(String email);
}

src/main/java/strona/bazapracownikow/view/DepartmentBean.java
package strona.bazapracownikow.view;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.validation.constraints.NotNull;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import strona.bazapracownikow.model.domain.Department;
import strona.bazapracownikow.model.service.DepartmentRepository;

/**
 *
 * @author shandnyar
 */
@Component
@Named
@RequestScoped
public class DepartmentBean implements Serializable {

    /**
     * Creates a new instance of DepartmentBean
     */
    @Autowired
    private DepartmentRepository departmentRepository;

    @NotNull
    private String name;

    private Department department;
    
    private UIComponent component;
    
    public DepartmentBean() {
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public UIComponent getComponent() {
        return component;
    }

    public void setComponent(UIComponent component) {
        this.component = component;
    }

    public Department getDepartment() {
        return department;
    }

    public String addDepartment() {
        if (departmentRepository.isDepartmentDuplicated(name)) {
            FacesContext ctx = FacesContext.getCurrentInstance();
            String message = ctx.getApplication().getResourceBundle(ctx, "msg").getString("departmentDuplicated");
            ctx.addMessage(component.getClientId(), new FacesMessage(message));
            return "";
        }
        Department departmentCreate = new Department();
        departmentCreate.setName(name);
        departmentRepository.create(departmentCreate);
        clear();
        return "showDepartments.jsf?faces-redirect=true";
    }
    
    public String showDepartment(long id) {
        department = departmentRepository.read(id);
        return "showDepartment.jsf";
    }
    
    public List<Department> getDepartments() {
        return departmentRepository.readAll();
    }
    
    public Map<String, Serializable> asMap() {
        Map results = new LinkedHashMap();
        for (Department d : departmentRepository.readAll()) {
            results.put(d.getName(), d.getId());
        }
        return results;
    }
    
    private void clear() {
        name = null;
    }
}

src/main/java/strona/bazapracownikow/view/LanguageBean.java
package strona.bazapracownikow.view;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import javax.inject.Named;

/**
 *
 * @author shandnyar
 */
@Named
@SessionScoped
public class LanguageBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private String localeCode;

    private static Map<String, Locale> countries;

    static {
        countries = new LinkedHashMap<String, Locale>();
        countries.put("Polski", new Locale("pl"));
//        countries.put("English", Locale.ENGLISH);
        countries.put("Deutsch", Locale.GERMAN);
    }

    public Map<String, Locale> getCountriesInMap() {
        return countries;
    }

    public String getLocaleCode() {
        return localeCode;
    }

    public void setLocaleCode(String localeCode) {
        this.localeCode = localeCode;
    }

    //value change event listener
    public void countryLocaleCodeChanged(ValueChangeEvent e) {

        localeCode = e.getNewValue().toString();

        //loop country map to compare the locale code
        for (Map.Entry<String, Locale> entry : countries.entrySet()) {

            if (entry.getValue().toString().equals(localeCode)) {

                FacesContext.getCurrentInstance()
                        .getViewRoot().setLocale((Locale) entry.getValue());

            }
        }
    }

}

src/main/java/strona/bazapracownikow/view/LoginBean.java
package strona.bazapracownikow.view;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.validation.constraints.Size;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import strona.bazapracownikow.model.domain.Manager;
import strona.bazapracownikow.model.service.ManagerRepository;

@Component
@Named
@SessionScoped
public class LoginBean implements Serializable {

    @Autowired
    private ManagerRepository managerRepository;

    private String email;
    @Size(min=3)
    private String password;

    private Manager manager;

    private UIComponent component;

    public UIComponent getComponent() {
        return component;
    }

    public void setComponent(UIComponent component) {
        this.component = component;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /*
    
    pare złów. według mnie, korzystanie z listenera jest czymś wolnym.
    
    */
    public String valid() {
        FacesContext ctx = FacesContext.getCurrentInstance();
        if (null != (manager = managerRepository.validManager(email, password))) {
            ctx.getApplication().getNavigationHandler().handleNavigation(ctx, null, "index.jsf");
            return "index.jsf?faces-redirect=true";
        } else {
            ResourceBundle bundle = ctx.getApplication().getResourceBundle(ctx, "msg");
            String message = bundle.getString("failedLogin");
            ctx.addMessage(component.getClientId(), new FacesMessage(message));
            return null;
        }
    }
    
    public String logout() {
        manager = null;
        return "index.jsf?faces-redirect=true";
    }

    public Manager getManager() {
        return manager;
    }

}

src/main/java/strona/bazapracownikow/view/ManagerBean.java
package strona.bazapracownikow.view;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.validation.constraints.Size;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import strona.bazapracownikow.model.domain.Manager;
import strona.bazapracownikow.model.service.ManagerRepository;
import strona.bazapracownikow.utils.HashUtil;

/**
 *
 * @author shandnyar
 */
@Component
@Named
@RequestScoped
public class ManagerBean implements Serializable {
    
    @Autowired
    private ManagerRepository managerRepository;

    private String email;
    @Size(min = 6, max = 20)
    private String password;
    private String firstName;
    private String lastName;
    
    private UIComponent component;
    
    public ManagerBean() {
    }

    public String addManager() {
        if (managerRepository.isManagerDuplicated(email)) {
            FacesContext ctx = FacesContext.getCurrentInstance();
            ResourceBundle bundle = ctx.getApplication().getResourceBundle(ctx, "msg");
            String message = bundle.getString("emailDuplicated");
            ctx.addMessage(component.getClientId(), new FacesMessage(message));
            return "";
        }
        Manager manager = new Manager();
        manager.setEmail(email);
        manager.setPassword(HashUtil.crypt(password));
        manager.setFirstName(firstName);
        manager.setLastName(lastName);
        manager.setStillWorking(true);
        managerRepository.create(manager);
        clear();
        return "registerSuccess.jsf";
    }

    public UIComponent getComponent() {
        return component;
    }

    public void setComponent(UIComponent component) {
        this.component = component;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    private void clear() {
        email = firstName = lastName = password = null;
    }
}

src/main/java/strona/bazapracownikow/view/WorkerBean.java
package strona.bazapracownikow.view;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.enterprise.context.RequestScoped;
import javax.faces.event.ValueChangeEvent;
import javax.inject.Named;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import strona.bazapracownikow.model.domain.Worker;
import strona.bazapracownikow.model.service.DepartmentRepository;
import strona.bazapracownikow.model.service.WorkerRepository;

/**
 *
 * @author shandnyar
 */
@Component
@Named
@RequestScoped
public class WorkerBean implements Serializable {

    /**
     * Creates a new instance of WorkerBean
     */
    @Autowired
    private WorkerRepository workerRepository;

    @Autowired
    private DepartmentRepository departmentRepository;

    private String firstName;
    private String lastName;
    private Date dateOfBirth;
    private double salary;
    private long departmentId;

    public WorkerBean() {
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public double getSalary() {
        return salary;
    }

    public void setSalary(double salary) {
        this.salary = salary;
    }

    public List<Worker> getWorkers() {
        return workerRepository.readAll();
    }

    public long getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(long departmentId) {
        this.departmentId = departmentId;
    }

    public String addWorker() {
        Worker worker = new Worker();
        worker.setFirstName(firstName);
        worker.setLastName(lastName);
        worker.setSalary(salary);
        worker.setDateOfBirth(dateOfBirth);
        worker.setDepartment(departmentRepository.read(departmentId));
        worker.setStillWorking(false);
        workerRepository.create(worker);
        clear();
        return "showWorkers.jsf?faces-redirect=true";
    }
    
    public String delWorker(Worker worker) {
        workerRepository.delete(worker);
        return null;
    }

    public void departmentChanged(ValueChangeEvent e) {
        departmentId = (Long) e.getNewValue();
    }

    private void clear() {
        firstName = lastName = null;
        departmentId = 0l;
        salary = 0;
        dateOfBirth = null;
    }

}

src/main/webapp/addDepartment.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="tpl/layout.xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    
    <ui:define name="title">
        #{msg.addDepartment}
    </ui:define>
    
    <ui:define name="content">
        <c:choose>
            <c:when test="#{!empty loginBean.manager}">
            <h:outputText id="message" value="" binding="#{departmentBean.component}" />
            <h:message for="message"/>
            <h:form styleClass="form-horizontal">
                <div class="form-group">
                    <h:outputLabel styleClass="col-sm-2 control-label"  for="name" value="#{msg.name}"/>
                    <div class="col-sm-10">
                        <h:inputText styleClass="form-control" id="name" value="#{departmentBean.name}" />
                    </div>
                    <h:message style="color:red;" for="name" />
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <h:commandButton styleClass="btn btn-default" action="#{departmentBean.addDepartment}" value="#{msg.addDepartment}">
                            <f:ajax render="@this" execute="@form" />
                        </h:commandButton>
                    </div>
                </div>
            </h:form>
            </c:when>
            <c:otherwise>
                <div class="alert alert-danger">
                    #{msg.notLoggedIn}
                </div>
            </c:otherwise>
        </c:choose>
    </ui:define>
</ui:composition>

src/main/webapp/addManager.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    template="tpl/layout.xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">
        #{msg.addManager}
    </ui:define>

    <ui:define name="content">
        <h:outputText id="message" value="" binding="#{managerBean.component}" />
        <h:message for="message"/>
        <h:form id="form" styleClass="form-horizontal">
            <div class="form-group">
                <h:outputLabel styleClass="col-sm-2 control-label"  for="email" value="#{msg.email}"/>
                <div class="col-sm-7">
                    <h:inputText styleClass="form-control" required="true" id="email" value="#{managerBean.email}">
                        <f:validator validatorId="emailValidator" />
                        <f:ajax event="keyup" execute="@this" render="emailMsg" />
                    </h:inputText>
                </div>
                <div class="col-sm-3">
                    <h:message style="color:red;" for="email" id="emailMsg"/>
                </div>
            </div>
            <div class="form-group">
                <h:outputLabel styleClass="col-sm-2 control-label"  for="password" value="#{msg.password}"/>
                <div class="col-sm-7">
                    <p:password styleClass="form-control" feedback="true" promptLabel="#{msg.passwordPromptLabel}" weakLabel="#{msg.passwordWeakLabel}" goodLabel="#{msg.passwordGoodLabel}" strongLabel="#{msg.passwordStrongLabel}" required="true" id="password" match="password1" value="#{managerBean.password}" />
                </div>
                <div class="col-sm-3">
                    <h:message style="color:red;" for="password" />
                </div>
            </div>
            <div class="form-group">
                <h:outputLabel styleClass="col-sm-2 control-label"  for="password" value="#{msg.repeatPassword}"/>
                <div class="col-sm-7">
                    <p:password styleClass="form-control" required="true" id="password1" value="#{managerBean.password}">
                        <f:validateLength minimum="6" maximum="20" />
                        <p:ajax event="keyup" update="msgPassword" />
                    </p:password>
                </div>
                <div class="col-sm-3">
                    <p:message for="password" id="msgPassword" display="icon"/>  
                </div>
            </div>
            <div class="form-group">
                <h:outputLabel styleClass="col-sm-2 control-label"  for="firstName" value="#{msg.firstName}"/>
                <div class="col-sm-7">
                    <h:inputText styleClass="form-control" id="firstName" required="true" value="#{managerBean.firstName}" />
                </div>
                <div class="col-sm-3">
                    <h:message style="color:red;" for="firstName" />
                </div>
            </div>
            <div class="form-group">
                <h:outputLabel styleClass="col-sm-2 control-label"  for="lastName" value="#{msg.lastName}"/>
                <div class="col-sm-7">
                    <h:inputText styleClass="form-control" id="lastName" value="#{managerBean.lastName}" />
                </div>
                <div class="col-sm-3">
                    <h:message style="color:red;" for="lastName" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <p:commandButton styleClass="btn btn-default" update="form" action="#{managerBean.addManager}" value="#{msg.addManager}" ajax="false">

                    </p:commandButton>
                </div>
            </div>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/addWorker.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
                template="tpl/layout.xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    
    <ui:define name="title">
        #{msg.addWorker}
    </ui:define>
    
    <ui:define name="content">
        <c:choose>
            <c:when test="${departmentBean.departments.isEmpty()}">
                <div class="alert alert-info">
                    <a href="addDepartment.jsf">#{msg.emptyDepartments}</a>
                </div>
            </c:when>
            <c:when test="#{!empty loginBean.manager}">
                <h:form styleClass="form-horizontal">
                    <div class="form-group">
                        <h:outputLabel styleClass="col-sm-2 control-label"  for="firstName" value="#{msg.firstName}"/>
                        <div class="col-sm-10">
                            <h:inputText styleClass="form-control" id="firstName" value="#{workerBean.firstName}" />
                        </div>
                        <h:message style="color:red;" for="firstName" />
                    </div>
                    <div class="form-group">
                        <h:outputLabel styleClass="col-sm-2 control-label"  for="lastName" value="#{msg.lastName}"/>
                        <div class="col-sm-10">
                            <h:inputText styleClass="form-control" id="lastName" value="#{workerBean.lastName}" />
                        </div>
                        <h:message style="color:red;" for="lastName" />
                    </div>
                    <div class="form-group">
                        <h:outputLabel styleClass="col-sm-2 control-label"  for="salary" value="#{msg.salary}"/>
                        <div class="col-sm-10">
                            <h:inputText styleClass="form-control" id="salary" value="#{workerBean.salary}" />
                        </div>
                        <h:message style="color:red;" for="salary" />
                    </div>
                    <div class="form-group">
                        <h:outputLabel styleClass="col-sm-2 control-label"  for="dateOfBirth" value="#{msg.dateOfBirth}"/>
                        <div class="col-sm-10">
                            <h:inputText styleClass="form-control" id="dateOfBirth" value="#{workerBean.dateOfBirth}">
                                <f:convertDateTime pattern="dd/MM/yyyy" />
                            </h:inputText>
                        </div>
                        <h:message style="color:red;" for="dateOfBirth" />
                    </div>
                    <div class="form-group">
                        <h:outputLabel styleClass="col-sm-2 control-label"  for="department" value="#{msg.department}"/>
                        <div class="col-sm-10">
                            <h:selectOneMenu styleClass="form-control" id="department" value="#{workerBean.departmentId}" valueChangeListener="#{workerBean.departmentChanged}">
                                <f:selectItems value="#{departmentBean.asMap()}"  />
                            </h:selectOneMenu>
                        </div>
                        <h:message style="color:red;" for="department" />
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <h:commandButton styleClass="btn btn-default" action="#{workerBean.addWorker()}" value="#{msg.addWorker}">

                            </h:commandButton>
                        </div>
                    </div>
                </h:form>
            </c:when>
            <c:otherwise>
                <div class="alert alert-danger">
                    #{msg.notLoggedIn}
                </div>
            </c:otherwise>
        </c:choose>
    </ui:define>
</ui:composition>

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
                template="tpl/layout.xhtml"
>
    <ui:define name="content">
    </ui:define>
</ui:composition>

src/main/webapp/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    template="tpl/layout.xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        #{msg.login}
    </ui:define>

    <ui:define name="content">
        <h:outputText id="message" value="" binding="#{loginBean.component}"/>
        <h:message for="message"/>
        <h:form styleClass="form-horizontal">
            <div class="form-group">
                <h:outputLabel styleClass="col-sm-2 control-label" for="email" value="#{msg.email}"/>
                <div class="col-sm-7">
                    <h:inputText styleClass="form-control" id="email" value="#{loginBean.email}" required="true">
                        <f:validator validatorId="emailValidator" />
                        <f:ajax execute="@this" event="keyup" render="emailMsg" />
                    </h:inputText>
                </div>
                <div class="col-sm-3">
                    <h:message style="color:red;" for="email" id="emailMsg" />
                </div>
            </div>
            <div class="form-group">
                <h:outputLabel styleClass="col-sm-2 control-label" for="password" value="#{msg.password}"/>
                <div class="col-sm-7">
                    <h:inputSecret styleClass="form-control" id="password" value="#{loginBean.password}" required="true">
                        <f:ajax execute="@this" event="keyup" render="passwordMsg" />
                    </h:inputSecret>
                </div>
                <div class="col-sm-3">
                    <h:message style="color:red;" for="password" id="passwordMsg" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <h:commandButton styleClass="btn btn-default" action="#{loginBean.valid()}" value="#{msg.login}">
                    </h:commandButton>
                </div>
            </div>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/showDepartments.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
                template="tpl/layout.xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:define name="title">
        #{msg.showDepartments}
    </ui:define>
    
    <ui:define name="content">
        <h:dataTable styleClass="table table-hover" value="#{departmentBean.departments}" var="department">
            <f:facet name="header">#{msg.allDepartmentsLabel}</f:facet>
            <h:column>
                <f:facet name="header">#{msg.name}</f:facet>
                <h:form>
                    <h:commandLink action="#{departmentBean.showDepartment(department.id)}" value="#{department.name}" />
                </h:form>
            </h:column>
            <h:column>
                <f:facet name="header">#{msg.amountOfWorkers}</f:facet>
                #{department.workers.size()}
            </h:column>
        </h:dataTable>
    </ui:define>
</ui:composition>